[package]
name = "pet-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aul = "1.3.1"
whdp = "1.1.8"
wjp = "1.0.1"
wbsl = { version = "0.0.0", path = "../wbsl" }